# Generated by Django 3.2 on 2024-02-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': ('Подписка',), 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': ('Пользователь',), 'verbose_name_plural': 'Пользователи'},
        ),
    ]
